version: '3.4'

services:
  yummyapi:
    image: yummyapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 317:317
